### PR TITLE
Port to Ubuntu Touch 20.04 (focal)

### LINKED ISSUE #21: [request] port to focal
Please update your essential app to focal if needed. Your app is a real document safe for me. I haven't switched to focal yet,  my 16.04 Volla is too personalized and stable for that, the focal ported environment (app) insufficient currently for me,  but at least other 20.04 users will be able to test. Thanks in advance.

### PR DESCRIPTION
**Pull request by JamiKettunen**
Closes #21.

@gbdomubpkm Would you mind testing all the app features when you test 20.04?

An upload of the new version to Focal channel @ https://open-store.io/app/tedit.fulvio would be appreciated once this happens :)

### CODE REVIEW

**Comment by JamiKettunen** [comment]
I did a bunch of quick tests of the features and think the app is good enough for an initial 20.04 release to OpenStore

**Comment by JamiKettunen** [comment]
@fulvio999 Would you have time to adjust version to 2.9.0 and push a `Focal` upload to https://open-store.io/app/tedit.fulvio or should someone fork the project and continue? I don't actively use this myself but made the PR on behalf of the people who use it on UT 16.04 and need it also on 20.04+

Though I could potentially maintain a fork enough to accept PRs and keep it running at least, I just wouldn't do active development of new features due to being busy with a lot of other things.

**Comment by fulvio999** [comment]
Hi @JamiKettunen , i would like that someone fork the App and continue his development and updating. Same thing for my other Apps. I can't maintain them anymore and stay updated with UBports.
Thanks

**Comment by gbdomubpkm** [comment]
Definitely want as a starting point a .click focal of the current xenial version when OTA-2 focal is released. One of the essential conditions to switch to focal for me and others. Thanks

**Comment by khurshid-alam** [comment]
Still no release for focal ? Is there a way I can manually install click packages ?

**Comment by gbdomubpkm** [comment]
Please, put at least a usable .click (test) here. Thank you.

**Comment by fulvio999** [comment]
Sorry but i don't know how to create a .click package for Focal..... It almost two years that i can't follow the UBports developments.
I was convinced that someone have taken in charge my apps.
Time ago i have asked in the Ubports forum looking for a new developer ([ubports forum](https://forums.ubports.com/topic/8639/looking-for-a-new-apps-maintainer)) and seems that someone was interested as confirmed looking at the previous posts in this thread...
Have you tried to ask again in the UBports forum ? or contact [JamiKettunen](https://github.com/JamiKettunen) ? I know that he have forked the Tedit app.
Thanks

**Pull request merged**
